version: '3.3'

services:
  magicmirror:
    image: magic
    container_name: magic_container
    restart: always

    environment:
      - TZ=Europe/London

    ports:
      - 8080:8080
      - 8081:8081

    volumes:
      - ./config:/opt/magic_mirror/config
      - ./images:/opt/magic_mirror/modules/hosted_images
      - ./css/custom.css:/opt/magic_mirror/css/custom.css
